[versions]
champeau-jmh = "0.7.3"
hamkrest = "1.8.0.1"
jackson = "3.1.0"
jmh = "1.37"
jmhreport = "0.9.6"
junit = "5.11.4"
junit-platform-launcher = "1.9.3"
kotest = "6.1.7"
kotlin = "2.3.10"
kotlinx-benchmark = "0.4.16"
kotlinx-coroutines = "1.10.2"
kotlinx-serialization = "1.10.0"
mariadb-driver = "3.5.7"
maven-publish = "0.36.0"
okeydoke = "2.0.3"
postgres-driver = "42.7.10"
strikt = "0.34.1"
testcontainers = "2.0.3"
version-catalog-update = "1.1.0"
versions = "0.53.0"

[libraries]
hamkrest = { module = "com.natpryce:hamkrest", version.ref = "hamkrest" }
jackson-databind = { module = "tools.jackson.core:jackson-databind", version.ref = "jackson" }
jmh-core = { module = "org.openjdk.jmh:jmh-core", version.ref = "jmh" }
jmh-generator-bytecode = { module = "org.openjdk.jmh:jmh-generator-bytecode", version.ref = "jmh" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit-platform-launcher" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-property = { module = "io.kotest:kotest-property", version.ref = "kotest" }
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinx-benchmark-runtime = { module = "org.jetbrains.kotlinx:kotlinx-benchmark-runtime", version.ref = "kotlinx-benchmark" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
mariadb-driver = { module = "org.mariadb.jdbc:mariadb-java-client", version.ref = "mariadb-driver" }
okeydoke = { module = "com.oneeyedmen:okeydoke", version.ref = "okeydoke" }
postgres-driver = { module = "org.postgresql:postgresql", version.ref = "postgres-driver" }
strikt-core = { module = "io.strikt:strikt-core", version.ref = "strikt" }
strikt-jvm = { module = "io.strikt:strikt-jvm", version.ref = "strikt" }
testcontainers-bom = { module = "org.testcontainers:testcontainers-bom", version.ref = "testcontainers" }
testcontainers-junit5 = { module = "org.testcontainers:testcontainers-junit-jupiter", version.ref = "testcontainers" }
testcontainers-mariadb = { module = "org.testcontainers:testcontainers-mariadb", version.ref = "testcontainers" }
testcontainers-postgres = { module = "org.testcontainers:testcontainers-postgresql", version.ref = "testcontainers" }

[bundles]
jmh = [
    "jmh-core",
    "jmh-generator-bytecode",
]
junit = [
    "junit-jupiter",
    "junit-jupiter-api",
    "junit-jupiter-engine",
    "junit-platform-launcher",
]
kotest = [
    "kotest-assertions-core",
    "kotest-property",
    "kotest-runner-junit5",
]
strikt = [
    "strikt-core",
    "strikt-jvm",
]
testcontainers = [
    "testcontainers-bom",
    "testcontainers-junit5",
]
testcontainers-mariadb = [
    "mariadb-driver",
    "testcontainers-mariadb",
]
testcontainers-postgres = [
    "postgres-driver",
    "testcontainers-postgres",
]

[plugins]
jmh = { id = "me.champeau.jmh", version.ref = "champeau-jmh" }
jmhreport = { id = "io.morethan.jmhreport", version.ref = "jmhreport" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlinx-benchmark = { id = "org.jetbrains.kotlinx.benchmark", version.ref = "kotlinx-benchmark" }
maven-publish = { id = "com.vanniktech.maven.publish.base", version.ref = "maven-publish" }
version-catalog-update = { id = "nl.littlerobots.version-catalog-update", version.ref = "version-catalog-update" }
versions = { id = "com.github.ben-manes.versions", version.ref = "versions" }
