on:
  push:
    branches:
      - trunk
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Grab tag name
        uses: olegtarasov/get-tag@v2.1.4
        id: tagName
      - name: Setup Java
        uses: actions/setup-java@v4.7.1
        with:
          distribution: temurin
          java-version: 21
      - name: Publish
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVENCENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVENCENTRAL_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}
          RELEASE_SIGNING_ENABLED: true
          SONATYPE_AUTOMATIC_RELEASE: true
        run: ./gradlew publishToMavenCentral --no-configuration-cache --info -PreleaseVersion="2.22.4.0"
        shell: bash
