on:
  push:
    tags:
      - '*'
env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1
      - name: Grab tag name
        uses: olegtarasov/get-tag@v2.1.4
        id: tagName
      - name: Setup Java
        uses: actions/setup-java@v5.1.0
        with:
          distribution: temurin
          java-version: 21
      - name: Publish
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVENCENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVENCENTRAL_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}
        run: sh ./gradlew publish --no-configuration-cache --info -Psign=true -PreleaseVersion="${{ steps.tagName.outputs.tag }}" -PsigningKey="${{ secrets.SIGNING_KEY }}" -PsigningPassword="${{ secrets.SIGNING_PASSWORD }}"
