plugins {
    alias(libs.plugins.jmh)
}

description = "A friendly Kotlin Result type"

dependencies {
    testApi(libs.kotlin.test)
}

test {
    include("dev/forkhandles/**")
    scanForTestClasses true
    reports {
        junitXml.required = true
        html.required = true
    }
}

artifacts {
    archives sourcesJar, javadocJar
}
